name: Deploy Customer iOS App to AppCenter

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    # if: github.event.pull_request.merged == true
    runs-on: macos-14

    steps:
      - name: Selecting Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
        
      - name: Check Xcode version
        run: /usr/bin/xcodebuild -version
